# Specific configuration for each language. This configuration should be repeated for every supported language, including the nolanguage.yaml (no correct language detected).

# Some regexp patterns are generic but can filtered with keywords. Those keywords must appear to the left/right of the detection at a maximum character length, specified in this structure.
proximity_regexp_config:
   CreditCard:
       word_file: config/keywords_creditcard_es.txt
       left_span_len: 20
       right_span_len: 0

   FinancialData:
       word_file: config/keywords_financialdata_es.txt
       left_span_len: 20
       right_span_len: 0

   DNI_SPAIN:
       word_file: config/keywords_dni_spain_es.txt
       left_span_len: 20
       right_span_len: 0

   PHONE:
       word_file: config/keywords_phone_es.txt
       left_span_len: 20
       right_span_len: 0

   MOBILE:
       word_file: "config/keywords_mobile_es.txt"
       left_span_len: 20
       right_span_len: 0

# ML models used for the extraction of entities
detection:
    nlp_model : es_core_news_sm    # SpaCy model
    crf_ner_list: models/crf_professions_v1.joblib   # extra ners (professions)
    personal_email_detection: models/email_detector.joblib    # detection of corportive mails
    crf_ner_classic: "models/crf_classic_step1.joblib,models/crf_classic_step2.joblib,models/crf_classic_step3.joblib,models/crf_classic_step4.joblib,models/crf_classic_step5.joblib"    # detection of PER, ORG, LOC (classic NER)
    corp_mail_list: models/corp_mail_list.txt   # list with typical corporative mail names (one mail per line)

